name: Release package
on:  
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Heavily inspired by https://github.com/bdunderscore/modular-avatar/blob/d1288fd3357128aaa6faae82e45a336f2207c054/.github/workflows/build-release.yml
    - name: Get Name
      id: packageName
      uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8
      with:
        path: "package.json"
        prop_path: "name"
    - name: Get Version
      id: packageVersion
      uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8
      with:
        path: "package.json"
        prop_path: "version"
    - name: Set Environment Variables
      run: |
        echo "zipFile=${{ steps.packageName.outputs.prop }}-${{ steps.packageVersion.outputs.prop }}".zip >> $GITHUB_ENV
    - name: Zip Folder
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        zip -r ${{ env.zipFile }} . -x ".gitattributes" ".gitignore" ".git/*" ".github/*"
    - name: Make Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        generate_release_notes: true
        tag_name: ${{ steps.packageVersion.outputs.prop }}
        files: |
          ${{ env.zipFile }}
